#!/usr/bin/env python3
import sys
try:
    from pylinkirc import launcher
except ImportError:
    print("ERROR: Failed to import PyLink launcher module (pylinkirc.launcher).\n\nIf you are "
          "running PyLink from source, please install PyLink first using 'python3 "
          "setup.py install' (global install) or 'python3 setup.py install --user'"
          " (local install)\n")
    sys.exit(1)
else:
    if __name__ == '__main__':
        launcher.main()
